version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/happi
    - secure: "jb05cM6VjmcA+L1pwBUzKN9++tf8neLrxpUxTlFKEHBS2XNXRYbqJgdJMZ6xyf6e8AkjTMxDYo12oKhJPs0vPk34G49dEjQI/9+4+RcaQvzauGDJHJNPfu5VIZhyjxysn+y3T3mj9ttE9w1oh2+8EJPuhWNRDJxQPuZHKNiD6Uf/LtSO09HwK8ZBDbVebzOvQb0PJigqWlPED6JLaw1z67+v1sfznQ8gMAJadmOhxs974G72hF5hrD3N/3lhhR1stFXW1Uib9vQaYQDglD06SzXS4SE0JWBaNwVZSKOoSb1Bn3Vvh6rsRZMjvBZVNx6GPYgSe7cSpXA5TF4/qr5zqh6xQW+PqR9imHupWVFoojm1uA6Hn1TfawTSscsh1LOrb1q09CcCQz3KZ28QUXccf9Y49/C8NPNUjkt3Srne+Ky44O5XQhvALkQkUtuC4/hvW5jGeBJigR8HlGtNWeylOKldF7+KcwrWfA9pKMB4ok8a+Api6vi7f83Fv41WraQMql+uONlcZPLGXstcGobvLzbHQc+bxT72OrM29HBaMlchZWJwoiFaMvao7y1Gczg6diL7zz8Ho+SgOZ6drngxsSj169O7+fY1TzAfKbhvg7N4iOsiJBW/BzvSZhE/B2hw0fdi2s9v6U7oRjVQFi+nIZcdB+PXp2d58WgSTTLeF6w="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="happi"

    # The name of the conda package
    - CONDA_PACKAGE="happi"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS=""

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    # This makes the PIP-based Python 3.6 optional.
    - name: "Python 3.6 - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
