language: python
sudo: false
env:
  global:
    - OFFICIAL_REPO="pcdshub/happi"
    - secure : "K6ZUT5rnh85OcXUTV5ymalGGUhXrPI+3DhGZa1YSoTn8/D6M9laJcSu110bkPUuxBX1dgYfcmcbcRFpHPnA/oQXZIGMszDSQg9/CrUQFw4aeOzbtzPxLff59EdeBXjBL9k1aZPe/xFA7Xu7K8vKkx909xo11yH2CEHEIcLE0rj++UPjwMTIMKP7P10P9gpW0vBC4Odk12AVB8ZBL7fBCKRB8PDgyIsu8EtZsWuwNzt0RgB/t8SJfV6wfc6pzcRK7nIuWWAieUFkomL8pDyjxOMf/0psm3LVNMSy9l73OsGx49C+Wf0UMDdBdPSAO8MBSObotUldMMfrdtOj1Vw2/7Owu9S/SqDeVO1s9Jd2RE4mguGqZ1IHaH6ZOUahJKo1/Pp+ZFWGHJHLedXEd04OHy+HidCIxOIedBe+Jj1z/rs9AM1fovUEL7lqKRk3zSkVZUHaFj8kyWsp5CPvWLlKzLlSbN1VyCZOZ3yucNk7IeF8/36LhQta4Ncv4ozzmg1kBbmCduQ+48+86iOMj2rDW5YFpmyMDXKhZFb076LM1Mjl0buNk9+J553oAbUGC70RXtS+7n08WHkA2r3R5UAEgqJmcDmY/kUeKBSPBF2EJhw1A+4/RyzlfX2ehsVyBVxoXvF/0RPzhmvKdKs4zkgD0xDWOJlyJx9yFIS0mhARMoc8="
matrix:
  include:
      - python: 3.5
        env: PCDS_CHANNEL=pcds-tag  
      - python: 3.5
        env: PCDS_CHANNEL=pcds-dev
      - python: 3.6
        env: PCDS_CHANNEL=pcds-dev  
      - python: 3.6
        env:
           - BUILD_DOCS=1
           - PCDS_CHANNEL=pcds-tag
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --append channels $PCDS_CHANNEL
  - conda config --append channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a
  # Test conda build
  - conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION happi --file dev-requirements.txt
  - source activate test-environment
  # TODO: mongomock is not currently available via conda. Ultimately we should
  # probably build this ourselves, but until that day we resort to `pip`
  - pip install mongomock
script:
  - coverage run run_tests.py
  - coverage report -m
  - set -e
  # Build docs.
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY" && $BUILD_DOCS ]]; then
      pushd docs
      sphinx-autogen -o source/generated source/*.rst 
      make html
      popd
      # Publish docs.
      doctr deploy --deploy-repo lcls-pcds/skywalker-docs --deploy-branch-name master happi
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $PCDS_CHANNEL == 'pcds-tag' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' && $PCDS_CHANNEL == 'pcds-dev' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
