version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/happi
    - secure: "b4+2HtESR2Aft9x14M3Zj6VCLVHEHV+41SsSkr6vfH5wZwrLnl0FX0IUMNbu5Edu2fPpdXmFXkR/hsvIhyZ4CHMGmJhZnXyALQLPLcb++T8qpVjw6rk9uWoU6SmFijfqm9AhI6ryUjMGpi01rgzuDy5x13YTFW5DgiDkgy6uXkPc+uCXhlBimc8AXk537Cw899/OnBmrs+cK6ye+YEwFwJvWu/WqDe400aByntB7zREsjEL/x3IgGM6isChgD3GwzyR5ytAGiR5nF+q5zxQF+37WPkzPjLUjLgXumXQU7h+0nheAPdX20h3nX3csPa3qmy/9iuJWe8Sg4r40yscwCv/4dknr+jXlSW7Y4EiGZxYuNeIvCUfUSt0lRi8uuzyKHb5jD1NVrH5+JMPPpm5VJisvGK9OhqE5thHYHHVJs89ZRwb/PPq3EkvA7g4JOJEKBlPiwMjPBGDFcLvI6Q38ggjURLnHx8Fh0AHRU779nCFaUBIcSj5ooycao/6kCS3ztg3QTPJjmk1bUTjVMw4nRKm4+jIioS5zjrMXl/35jbqI/kRwAy6C0FGGT88xTcjsACTojLNMK54QKKny52OrywfttcJcX7HWGKhnCVdlFM4ij7EcZCMoXriOhbvC2xe20qUEScY57tMV1VnN+yp/ZmoS68autnsAPUmhzKX66Go="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="happi"

    # The name of the conda package
    - CONDA_PACKAGE="happi"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS=""

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
