{% set data = load_setup_py_data() %}
{% set name = "happi" %}

package:
    name: {{ name }}
    version: {{ data.get('version') }}

build:
  noarch: python
  number: 0

source:
    path: ..

requirements:
    build:
      - python >=3.6
      - pip
    run:
      - python >=3.6
      - click
      - coloredlogs
      - entrypoints
      - jinja2
      - prettytable
      - simplejson
    run-constrained:
      - psdm_qs_cli >=0.3.1
      - pymongo >=4.0.2

test:
    imports:
      - happi
    commands:
      - happi --help

    requires:
      - pytest
      - ipython

about:
  home: https://github.com/pcdshub/happi/
  doc_url: https://pcdshub.github.io/happi/
  dev_url: https://github.com/pcdshub/happi/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Heuristic Access to Positions of Photon Instruments
