{% set data = load_setup_py_data() %}

package:
    name    : happi
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
      - python


    run:
      - jinja2
      - prettytable
      - psdm_qs_cli  >=0.2.3
      - simplejson
      - pymongo 
      - python
test:
    imports:
      - happi

    requires: 
      - pytest

about:
  home: https://github.com/pcdshub/happi
  license: SLAC Open License
  summary: Heuristic Access to Positions of Photon Instruments
