{% set data = load_setup_py_data() %}

package:
    name    : happi
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
      - python


    run:
      - six
      - numpy
      - prettytable
      - pymongo 
      - python
      - simplejson
test:
    imports:
      - happi

    requires: 
      - pytest
